before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: DZjhPMOGgt0sAjCg1SsKUVz0e6x42+wCHQKEpucaK04Yzznu9+rmjtjZ84vFZ+6R2XeYQGJUNog179joWRkbDSXBK2jUSUCkwJ8JoQLcyRY12TrKh6EnKl5+efY/Flx4Useq0S27PdWtJtZdNVTTbVKO9OAlC06ljTJz5tx/Vr54uwlBAxQQySFLU9O4sAJqXppBh1eyQQiMZCM7rQDFDTiI1BHRDcwgkgZIUVkvAOpF3RToEk3DezgWZ+shpmRmo/lYUBkyIkzMDq4TVFKldohLLRLbVYzhgIo/4kuWvnYOsf+bLqVgfsFcoXew9X+RU1t08bnh17APAXktkb8LHg3v7emsTt2p5YA6YoI7ZDAFMAY2R6hHPfszrwIyEdDRp5dYsqRakvpFcPo/Fh7QTXoUBxSsMnMqsz7PkT4q3uOks/1iIa1wbrAAIs8mnLR+F7nKMVoU9qSj59/TWfoDBh/3IegYWWdydNjDqJ6FyQOHajprFBQwOb6taLMAL3ZZL+42D6VGkyEBF3ySfR940RBXWVf4LzKp75iLNQAC6Q+FUJwdZ6SjvCVrmOHX5/9apJHBTEifErf67EYkA81FL90BeOdRLBcUkbibYSXNfAhdBTDatuEEN2zdndr5Nzv60fuvfRqm168QLIKjuR7FlR0iSHai2gXbFOE6lrVCGNo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
